// Playbill data — Velocity 2026
window.PLAYBILL = {
  show: {
    title: "VELOCITY",
    studio: "Duggan's Dance Center",
    year: "2026",
  },

  welcome: {
    from: "Meagan Duggan Shoenfelt",
    role: "Owner & Creative Director",
    body: [
      "Welcome to VELOCITY — our 2026 Showcase.",
      "This year's theme is about momentum: the way a single step builds into a leap, the way a small idea becomes a season of work, the way a dancer becomes an artist. Every routine on tonight's stage is a piece of that energy made visible.",
      "To our dancers — you have shown up, day after day, with grit and grace. To our families — thank you for the rides, the rehearsals, the costumes, and the cheers. To our staff — thank you for pouring yourselves into this community. None of this happens without you.",
      "Sit back, light up, and let it move you.",
    ],
  },

  staff: {
    owner: { name: "Meagan Duggan Shoenfelt", role: "Owner & Creative Director" },
    teachers: [
      "Nicole Wright",
      "Kyra Rosenburg",
      "Jessie Robie",
      "Emma Brockett",
    ],
    assistants: [
      "Addison Sherry",
      "Avery Gelineau",
      "Hailey Wright",
      "Lili Shoenfelt",
      "Lillian Ghere",
      "Myla Madera",
      "Sabella Madera",
      "Savannah Boclair",
      "Sophia Castillo-Blain",
    ],
  },

  seniors: [
    {
      name: "Emma Sweet",
      photos: [window.__resources.seniorEmma1, window.__resources.seniorEmma2],
      quote: "Dance is the hidden language of the soul.",
      quoteBy: "Martha Graham",
    },
    {
      name: "Mikah Levenduski",
      photos: [window.__resources.seniorMikah1, window.__resources.seniorMikah2],
      quote: "To dance is to be out of yourself. Larger, more beautiful, more powerful.",
      quoteBy: "Agnes de Mille",
    },
  ],

  cast: [
    "Abigail Valdez","Addison Krynick","Addison Sherry","Adelaide Kingman","Ainsley Bagdonis",
    "Alice Durel","Alyssa Levenduski","Amber Valdez","Andromeda Mullane","Aria Kaplan",
    "Arya Pierce","Ashlyn McWade","Aurora Kaiser","Avery Gelineau","Avery Holzer",
    "Avery Leitch","Blake Aresco","Brenna Walsh","Bridget Walsh","Brielle Gelineau",
    "Caleigh Kitchin","Cali Wojick","Cameron Jurovaty","Carly Rodriguez","Cassandra Franklim",
    "Cassidy Grey","Celia Cooke","Charlotte Badeau","Charlotte Cyr","Chloe Poulin",
    "Cira Wilson","Coraline Mihalko","Elise Young","Ella Paternoster","Emma Dunn",
    "Emma Sweet","Evelyn Gnade","Evelyn Searles","Everly Monge","Faith Spence",
    "Gabriela Pero","Gabriella Serrano","Grace Paternoster","Gracey Bagdonis","Hailey Wright",
    "Hanna Spence","Harper Loiselle","Iris Mahoney","Ivy Congo","Jenna Pease",
    "Kaelyn Loiselle","Katherine White","Lennon Gasiewski","Lenox Piatek","Lianna Kilcollum",
    "Lili Shoenfelt","Lillian Ghere","Lillian Kazana","Lily Ekstowicz","Lilly Stino",
    "Lilyanne Bastarache","Logan Cavender","Loretta Heinen","Lucille Ghere","Madalyn Kinsey",
    "Maggie Gower","Malia Flynn","Marcella Doyle","Matthew Cudgma","Maya Herr",
    "Mialani Satavu","Michaela Westcott","Mikah Levenduski","Mikayla Peters","Milania White",
    "Milena Zygmunt","Molly McWade","Myla Madera","Natalie Watrous","Norah Zuba",
    "Olivia Carter","Olivia Mikulak","Paityn Hoffmann","Penelope Gnade","Pippa Gasiewski",
    "Raegan Dunagan","Raegan Moquin","Ramona Palermo","Rebecca Macierowski","Riley Mikulak",
    "Sabella Madera","Sadie Broughton","Samantha Westcott","Savannah Boclair","Scarlett Hungerford",
    "Sienna Carter","Skyleigh Boulet","Sofia Casal Oleynek","Sonja Palermo","Sophia Castillo-Blain",
    "Stella Cavanaugh","Sydney Alvey","Taylor Wright","Willow Mahon",
  ],

  program: [
    { n: 1, title: "Bloom", group: "Synergy Team", dancers: "Avery Gelineau, Avery Holzer, Avery Leitch, Emma Sweet, Hailey Wright, Kaelyn Loiselle, Lili Shoenfelt, Myla Madera, Reagan Moquin, Sabella Madera, Taylor Wright" },
    { n: 2, title: "Velvet Ring", dancers: "Addison Krynick" },
    { n: 3, title: "Isn't She Lovely", group: "Beginner Ballet 7+", dancers: "Alice Durel, Amber Valdez, Emma Dunn, Evelyn Gnade, Marcella Doyle, Milania White, Olivia Mikulak, Paityn Hoffmann, Sonja Palermo, Sophia Castillo-Blain, Willow Mahon" },
    { n: 4, title: "Vibrate", dancers: "Sabella Madera" },
    { n: 5, title: "Never Looked So Good", group: "Jr. Company Jazz", dancers: "Avery Gelineau, Brielle Gelineau, Carly Rodriguez, Lillian Ghere, Logan Cavender, Maggie Gower, Malia Flynn" },
    { n: 6, title: "No Time To Die", dancers: "Molly McWade" },
    { n: 7, title: "Just Breathe", group: "Advanced Acro Team", dancers: "Addison Krynick, Alyssa Levenduski, Avery Gelineau, Avery Leitch, Hailey Wright, Lili Shoenfelt, Myla Madera, Reagan Moquin, Sabella Madera, Taylor Wright" },
    { n: 8, title: "My Blood", dancers: "Lillian Ghere" },
    { n: 9, title: "Lose Control", group: "Intermediate Hip Hop Foundations", dancers: "Abigail Valdez, Addison Sherry, Brielle Gelineau, Cali Wojick, Cameron Jurovaty, Carly Rodriguez, Charlotte Badeau, Charlotte Cyr, Harper Loiselle, Lilyanne Bastarache, Logan Cavender, Loretta Heinen, Madalyn Kinsey, Maggie Gower, Marcella Doyle, Maya Herr, Mikayla Peters, Milania White, Paityn Hoffmann, Ramona Palermo, Sadie Broughton" },
    { n: 10, title: "We Go Together", group: "Tap 5-6", dancers: "Aurora Kaiser, Celia Cooke, Elise Young, Grace Paternoster, Lucille Ghere, Savannah Boclair" },
    { n: 11, title: "What Could've Been", group: "Elite", dancers: "Addison Krynick, Alyssa Levenduski, Avery Leitch, Hailey Wright, Lili Shoenfelt, Myla Madera, Reagan Moquin, Sabella Madera" },
    { n: 12, title: "Best Life", group: "Mini Jazz Team", dancers: "Amber Valdez, Marcella Doyle, Milania White, Olivia Mikulak, Sonja Palermo, Sophia Castillo-Blain, Willow Mahon" },
    { n: 13, title: "Body Double", dancers: "Myla Madera, Sabella Madera" },
    { n: 14, title: "I Just Can't Wait To Be King", group: "Beginner Ballet 5-6", dancers: "Adelaide Kingman, Celia Cooke, Isla DeSorbo, Lianna Kilcollum, Lucille Ghere, Natalie Watrous, Norah Zuba, Riley Mikulak, Scarlett Hungerford, Sofia Casal Oleynek, Stella Cavanaugh", assistant: "Lillian Ghere" },
    { n: 15, title: "Don't Get Me Started", dancers: "Lili Shoenfelt" },
    { n: 16, title: "Abracadabra", group: "Jazz Foundations 9+", dancers: "Abigail Valdez, Ashlyn McWade, Avery Gelineau, Caleigh Kitchin, Charlotte Badeau, Emma Sweet, Harper Loiselle, Lillian Ghere, Maya Herr, Myla Madera, Sabella Madera" },
    { n: 17, title: "Easy", dancers: "Addison Krynick, Alyssa Levenduski" },
    { n: 18, title: "Material Girl", dancers: "Carly Rodriguez" },
    { n: 19, title: "Groove Is In The Heart", group: "Tap Team", dancers: "Avery Holzer, Hailey Wright, Molly McWade, Taylor Wright" },
    { n: 20, title: "Cradles", dancers: "Myla Madera" },
    { n: 21, title: "Trolls", group: "Jazz 5-8", dancers: "Amber Valdez, Cassidy Grey, Elise Young, Iris Mahoney, Lucille Ghere, Mialani Satavu, Natalie Watrous, Olivia Mikulak, Riley Mikulak, Scarlett Hungerford" },
    { n: 22, title: "Feel the Bass", dancers: "Mikah Levenduski" },
    { n: 23, title: "Warriors", group: "Intermediate/Advanced Acro", dancers: "Abigail Valdez, Addison Sherry, Avery Gelineau, Avery Leitch, Blake Aresco, Cameron Jurovaty, Coraline Mihalko, Hailey Wright, Harper Loiselle, Lili Shoenfelt, Mikayla Peters, Myla Madera, Rebecca Macierowski, Sabella Madera" },
    { n: 24, title: "Friend Like Me", group: "Tiny Tumblers", dancers: "Lillian Kazana, Matthew Cudgma, Penelope Gnade, Raegan Dunagan, Sydney Alvey", assistant: "Hailey Wright, Lili Shoenfelt, Lillian Ghere, Myla Madera, Savannah Boclair, Sophia Castillo-Blain" },
    { intermission: true },
    { n: 25, title: "My Name On It", group: "Intermediate Acro", dancers: "Abigail Valdez, Ainsley Bagdonis, Amber Valdez, Bridget Walsh, Brielle Gelineau, Charlotte Badeau, Katherine White, Lennon Gasiewski, Lillian Ghere, Lilyanne Bastarache, Lily Ekstowicz, Madalyn Kinsey, Pippa Gasiewski, Ramona Palermo, Sonja Palermo" },
    { n: 26, title: "Footloose", group: "Beginner Acro 5+", dancers: "Andromeda Mullane, Aria Kaplan, Evelyn Gnade, Gabriela Pero, Gabriella Serrano, Iris Mahoney, Jenna Pease, Lenox Piatek, Lucille Ghere, Mialani Satavu, Michaela Westcott, Samantha Westcott, Savannah Boclair", assistant: "Addison Sherry, Hailey Wright, Lillian Ghere" },
    { n: 27, title: "Sleeping Beauty Variation", group: "Pointe", dancers: "Avery Holzer, Hailey Wright, Lili Shoenfelt, Molly McWade, Myla Madera, Reagan Moquin, Sabella Madera" },
    { n: 28, title: "Na Na Na", group: "Tap 7-11", dancers: "Cali Wojick, Sophia Castillo-Blain, Willow Mahon" },
    { n: 29, title: "To Build A Home", dancers: "Brielle Gelineau, Logan Cavender" },
    { n: 30, title: "Everywhere, Everything", group: "Contemporary 7+", dancers: "Ashlyn McWade, Blake Aresco, Faith Spence, Harper Loiselle, Skyleigh Boulet" },
    { n: 31, title: "Gossip Folks", dancers: "Avery Holzer, Avery Leitch" },
    { n: 32, title: "Unforgettable", dancers: "Sabella Madera" },
    { n: 33, title: "Work Song", group: "Tiny Tutus", dancers: "Aurora Kaiser, Chloe Poulin, Cira Wilson, Evelyn Searles, Gracey Bagdonis, Ivy Congo", assistant: "Lili Shoenfelt" },
    { n: 34, title: "I Am Music", dancers: "Myla Madera" },
    { n: 35, title: "Fourth of July", dancers: "Reagan Moquin" },
    { n: 36, title: "Crimson", group: "Junior Company Contemporary", dancers: "Brielle Gelineau, Carly Rodriguez, Lillian Ghere, Logan Cavender, Maggie Gower, Malia Flynn, Milania White, Willow Mahon" },
    { n: 37, title: "Nothing's New", dancers: "Alyssa Levenduski" },
    { n: 38, title: "Whip My Hair", group: "Beginner Hip Hop Foundation", dancers: "Andromeda Mullane, Aria Kaplan, Arya Pierce, Ella Paternoster, Everly Monge, Gabriela Pero, Grace Paternoster, Hanna Spence, Iris Mahoney, Lenox Piatek, Lucille Ghere, Milena Zygmunt, Olivia Carter, Sienna Carter, Stella Cavanaugh" },
    { n: 39, title: "Back to Black", dancers: "Avery Leitch" },
    { n: 40, title: "Giselle's Friends", group: "Intermediate Ballet", dancers: "Abigail Valdez, Addison Sherry, Avery Gelineau, Blake Aresco, Brenna Walsh, Brielle Gelineau, Cameron Jurovaty, Carly Rodriguez, Faith Spence, Harper Loiselle, Lillian Ghere, Lilly Stino, Logan Cavender, Maggie Gower, Malia Flynn, Ramona Palermo" },
    { n: 41, title: "I Love You", dancers: "Lili Shoenfelt" },
    { n: 42, title: "Huntrix", group: "Harmony Team", dancers: "Aria Kaplan, Gabriela Pero, Lucille Ghere" },
    { n: 43, title: "Primavera", group: "Advanced Ballet", dancers: "Addison Krynick, Alyssa Levenduski, Avery Holzer, Avery Leitch, Hailey Wright, Kaelyn Loiselle, Lili Shoenfelt, Molly McWade, Myla Madera, Reagan Moquin, Sabella Madera" },
    { n: 44, title: "Back To December", dancers: "Emma Sweet" },
    { n: 45, title: "Undone", group: "Junior Acro Team", dancers: "Abigail Valdez, Lillian Ghere, Lilly Stino, Marcella Doyle, Paityn Hoffmann, Ramona Palermo, Sophia Castillo-Blain, Willow Mahon" },
    { n: 46, title: "Battlefield", dancers: "Maggie Gower" },
    { n: 47, title: "Just Keep Watching", group: "Company Jazz", dancers: "Addison Krynick, Alyssa Levenduski, Avery Leitch, Hailey Wright, Kaelyn Loiselle, Lili Shoenfelt, Molly McWade, Myla Madera, Reagan Moquin, Sabella Madera, Taylor Wright" },
    { n: 48, title: "One Beautiful Evening", dancers: "Mikah Levenduski" },
    { n: 49, title: "Think Too Much", dancers: "Emma Brockett" },
    { n: 50, title: "Risotto", dancers: "Myla Madera, Sabella Madera" },
    { n: 51, title: "Party Up", group: "Fusion", dancers: "Abigail Valdez, Carly Rodriguez, Charlotte Cyr, Logan Cavender, Madalyn Kinsey, Maggie Gower, Marcella Doyle, Milania White, Ramona Palermo" },
    { n: 52, title: "Extraordinary Magic", dancers: "Willow Mahon" },
    { n: 53, title: "On Then And Now", group: "Company Contemporary", dancers: "Addison Krynick, Alyssa Levenduski, Avery Leitch, Hailey Wright, Kaelyn Loiselle, Lili Shoenfelt, Molly McWade, Myla Madera, Reagan Moquin, Sabella Madera, Taylor Wright" },
    { n: 54, title: "Runaway", dancers: "Brielle Gelineau" },
    { n: 55, title: "Girls", dancers: "Milania White" },
    { n: 56, title: "Soulja Boy", group: "Advanced Hip Hop Foundations", dancers: "Avery Gelineau, Avery Holzer, Avery Leitch, Cassandra Franklim, Emma Sweet, Hailey Wright, Kaelyn Loiselle, Lili Shoenfelt, Myla Madera, Reagan Moquin, Sabella Madera, Taylor Wright" },
    { n: 57, title: "Wildflower", dancers: "Logan Cavender" },
    { n: 58, title: "Hero", dancers: "Jessie Robie" },
    { n: 59, title: "Descendants", group: "Musical Theater Team", dancers: "Addison Krynick, Alyssa Levenduski, Avery Holzer, Cassandra Franklim, Carly Rodriguez, Emma Sweet, Hailey Wright, Harper Loiselle, Kaelyn Loiselle, Lili Shoenfelt, Lillian Ghere, Mikayla Peters, Molly McWade, Myla Madera, Paityn Hoffmann, Reagan Moquin, Sabella Madera, Sonja Palermo, Taylor Wright, Willow Mahon" },
  ],

  ads: [
    { src: window.__resources.ad1, alt: "Class of 2026 — Emma Sweet" },
    { src: window.__resources.ad2, alt: "Class of 2026 — Mikah Levenduski" },
    { src: window.__resources.ad3, alt: "Congratulations Lilly & Willow" },
    { src: window.__resources.ad4, alt: "Avery Elizabeth" },
    { src: window.__resources.ad5, alt: "Addy, Alyssa & Sophie" },
    { src: window.__resources.ad6, alt: "Emma Jordan" },
    { src: window.__resources.ad7, alt: "S.K. Painting LLC" },
    { src: window.__resources.ad8, alt: "Stella & Wdov-Co Crane" },
    { src: window.__resources.ad9, alt: "Carly R" },
  ],
};
